### PR TITLE
Improved test coverage

### PR DESCRIPTION
**Pull request by Kenny-MWI**
This pull request brings code coverage up to 80% of lines tested and nearly 50% of the methods tested. I'm not sure how to make meaningful tests for the remaining methods. Some of these are due to the Nova integration and others are due to model relationships that depend on packages not required by this one. 

```txt
Code Coverage Report:      
  2021-04-21 19:47:42      
                           
 Summary:                  
  Classes: 45.45% (5/11)   
  Methods: 49.18% (30/61)  
  Lines:   80.23% (142/177)

Tipoff\Authorization\AuthorizationServiceProvider
  Methods:  66.67% ( 2/ 3)   Lines:  96.15% ( 25/ 26)
Tipoff\Authorization\Commands\AuthorizationCommand
  Methods:   0.00% ( 0/ 1)   Lines:   0.00% (  0/  1)
Tipoff\Authorization\Models\EmailAddress
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% (  2/  2)
Tipoff\Authorization\Models\User
  Methods:  30.00% ( 6/20)   Lines:  48.57% ( 17/ 35)
Tipoff\Authorization\Nova\EmailAddress
  Methods: 100.00% ( 3/ 3)   Lines: 100.00% ( 11/ 11)
Tipoff\Authorization\Nova\User
  Methods:  83.33% ( 5/ 6)   Lines:  97.06% ( 33/ 34)
Tipoff\Authorization\Permissions\BasePermissionsMigration
  Methods: 100.00% ( 4/ 4)   Lines: 100.00% ( 29/ 29)
Tipoff\Authorization\Policies\PermissionPolicy
  Methods:   0.00% ( 0/ 7)   Lines:   0.00% (  0/  7)
Tipoff\Authorization\Policies\RolePolicy
  Methods:   0.00% ( 0/ 7)   Lines:   0.00% (  0/  7)
Tipoff\Authorization\Policies\UserPolicy
  Methods: 100.00% ( 7/ 7)   Lines: 100.00% (  7/  7)
Tipoff\Authorization\Providers\TipoffUserProvider
  Methods: 100.00% ( 1/ 1)   Lines: 100.00% ( 18/ 18)
```

### CODE REVIEW

**Comment by pdbreen** [comment]
Recommend:
* delete src/Commands/AuthorizationCommand.php
* extend Unit/Models/UserTest.php to test `User::cart(..)` with and without CartInterface being mocked
* extend Unit/Models/UserTest.php to test `User::getEmailVerifiedAtAttribute()`

Optional - exclude untestable User model relations from coverage reporting
* Use `@codeCoverageIgnoreStart` and `@codeCoverageIgnoreEnd` markers for the untestable relations in User model

Optional - add missing policy tests (policy tests really don't add much value, but they are missing)
* add new Unit/Policies/RolePolicyTest.php
* add new Unit/Policies/PermissionPolicyTest.php

**Comment by drewroberts** [comment]
@jasonmccreary Can you also review this and think about what tests would be best for this authorization package?

**Comment by jasonmccreary** [comment]
@drewroberts, that's hard to say without diving into the code. Generally speaking I don't seek 100% test coverage. It really doesn't _mean_ anything to have. In fact, it can give false confidence or poor testing practices to achieve.

I'm glad to check out the code and give this package a "test audit". Just let me know.

But there's nothing here that should prevent a merge first.

**Review by drewroberts — APPROVED** [review]
Thank you! 🎶

**Pull request merged**
